# @see https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/index.md
sylius_resource:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'

    resources:
        app.query:
            driver: doctrine/orm
            classes:
                model: App\Entity\Query
